tasks:
  - init: pyenv local 3.9
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - charliermarsh.ruff
    - christian-kohler.path-intellisense
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.vscode-github-actions
    - ms-python.mypy-type-checker
    - ms-python.python
    - ms-python.vscode-pylance
    - redhat.vscode-yaml
    - ryanluker.vscode-coverage-gutters
    - soulcode.vscode-unwanted-extensions
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
    - yzhang.markdown-all-in-one
