# cspell:ignore doctests unittests

name: CI-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    name: Unit tests + coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Test with pytest-cov
        run: pytest tests --cov=sphinxcontrib.hep.pdgref --cov-report=xml
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests

  pytest:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macos-10.15
            python-version: 3.6
          - os: macos-10.15
            python-version: 3.8
          - os: macos-10.15
            python-version: 3.9
          - os: ubuntu-20.04 # coverage job
            python-version: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Test with pytest
        run: pytest tests
      # cspell:ignore IMPORTMISMATCH
      - name: Run doctests
        run: PY_IGNORE_IMPORTMISMATCH=1 pytest src
