# cspell:ignore autoupdate noreply reqs

name: Requirements (scheduled)

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  upgrade-pre-commit:
    name: Upgrade pre-commit hooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Perform style checks
        run: pre-commit autoupdate
      - uses: actions/upload-artifact@v2
        with:
          path: .pre-commit-config.yaml

  push:
    name: Create PR
    runs-on: ubuntu-20.04
    needs:
      - upgrade-pre-commit
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v2
        with:
          path: .
      - run: git status -s
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: upgrade developer dependencies"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: "ci: upgrade developer dependencies"
          labels: |
            🖱️ DX
          branch-suffix: timestamp
          delete-branch: true
          token: ${{ secrets.PAT }}
      - name: Print PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
